
bootstrap:
  '@nikitajs/core/lib/ssh/open':
    disabled: false
    host: 'X.X.X.X'
    port: 22
    password: 'XXXX'
  './lib/bootstrap/2.disk':
    passphrase: 'XXXX'
  './lib/bootstrap/3.system':
    locales: ['fr_FR.UTF-8', 'en_US.UTF-8']
    timezone: 'Europe/Paris'
    users:
      nikita:
        uid: 1000
        password: 'secret'
        sudoer: true
    install_bumblebee: false

system:
    # Groups of packages to install
    './lib/system/2.dev_apps':
        gnome: true
        virtualization: true
        docker: true
        virtualbox: true
        npm_global: true
        atom: true
        nodejs: true
        programming: true

    './lib/system/3.office_apps':
        productivity: true
        font: true
        office: true
